### ISSUE TITLE
在切換 scene 的時候保持畫面大小

### ISSUE THREAD

**Issue by liuyenting** [liuyenting/FwdRevDesign#6]
需要在 state 當中額外針對 scene 的切換，調整底層 anchor pane 的大小。

**Comment by CTinRay** [comment]
`stage.hide();`的時候
視窗就不見了吧

**Comment by liuyenting** [comment]
直接關掉不會影響，因為 setScene 會導致 pane 的 info 流失。
不過 stage.hide() 的確等價於 stage.close()，但不代表 stage 這個物件不見了。

**Comment by CTinRay** [comment]
好吧
也許我不知到你在問什麼

**Comment by liuyenting** [comment]
Fixed at 0975c64.
